# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='NO TITLE', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('imageUrl', models.CharField(blank=True, default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=500)),
                ('bias', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
